init:
  - git config --global core.autocrlf input

shallow_clone: true

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5.5.0"
    - nodejs_version: "6"
    - nodejs_version: "8"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - pip install --egg scons
  - node --version
  - npm -g install npm@next
  - npm --version
  - npm install -g grunt-cli

test_script:
  - ps: npm install -g "$(npm pack)"
  - npm install --ignore-scripts
  - npm link iotivity-node
  - grunt test --ci

build: off
